<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find tinker_description)/urdf/base/base.gazebo.xacro"/>
    <xacro:include filename="$(find tinker_description)/urdf/sensor/hokuyo_lx30_laser.urdf.xacro"/>
    <xacro:include filename="$(find hector_sensors_description)/urdf/realsense_camera.urdf.xacro"/>

    <xacro:property name="base_length" value="0.64"/>
    <xacro:property name="base_width" value="0.52"/>
    <xacro:property name="base_height" value="0.18"/>

    <xacro:property name="base_laser_x" value="0.30"/>
    <xacro:property name="base_laser_y" value="0"/>
    <xacro:property name="base_laser_z" value="0.25"/>

    <xacro:property name="front_primesense_x" value="0.40"/>
    <xacro:property name="front_primesense_y" value="0"/>
    <xacro:property name="front_primesense_z" value="0.1"/>

    <xacro:property name="back_xtion_x" value="-0.30"/>
    <xacro:property name="back_xtion_y" value="0"/>
    <xacro:property name="back_xtion_z" value="0.1"/>


    <!--*****************chasiss***********************-->
    <link name="virtual_x_link">
        <inertial>
            <mass value="1"/>
            <inertia ixx="0.1" ixy="0.1" ixz="0.1" iyy="0.1" iyz="0.1" izz="0.1"/>
        </inertial>
    </link>
    <joint name="virtual_x_joint" type="prismatic">
        <parent link="virtual_x_link" />
        <child link="virtual_y_link" />
        <origin rpy="0 0 0" />
        <limit lower="-1000" upper="1000" velocity="0.2" effort="10000"/>
    </joint>

    <link name="virtual_y_link">
        <inertial>
            <mass value="1"/>
            <inertia ixx="0.1" ixy="0.1" ixz="0.1" iyy="0.1" iyz="0.1" izz="0.1"/>
        </inertial>
    </link>
    <joint name="virtual_y_joint" type="prismatic">
        <parent link="virtual_y_link" />
        <child link="virtual_yaw_link" />
        <origin rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="-1000" upper="1000" velocity="0.2" effort="10000"/>
    </joint>

    <link name="virtual_yaw_link">
        <inertial>
            <mass value="1"/>
            <inertia ixx="0.1" ixy="0.1" ixz="0.1" iyy="0.1" iyz="0.1" izz="0.1"/>
        </inertial>
    </link>
    <joint name="virtual_yaw_joint" type="continuous">
        <parent link="virtual_yaw_link" />
        <child link="base_link" />
        <origin rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit velocity="0.2" effort="10000"/>
    </joint>


    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}"/>
            <material name="brown"/>
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}"/>
        </collision>

        <inertial>
            <origin xyz="0 0 ${base_height/2}"/>
            <mass value="1"/>
            <inertia ixx="0.1" ixy="0.1" ixz="0.1" iyy="0.1" iyz="0.1" izz="0.1"/>
        </inertial>
    </link>

    <xacro:hokuyo_lx30_laser_v0 name="base_laser" parent="base" ros_topic="scan" update_rate="20"
                                min_angle="${-3*M_PI/4}" max_angle="${3*M_PI/4}">
        <origin xyz="${base_laser_x} ${base_laser_y} ${base_laser_z}" rpy="0 0 0"/>
    </xacro:hokuyo_lx30_laser_v0>

    <xacro:realsense_camera name="primesense_front" parent="base_link">
        <origin xyz="${front_primesense_x} ${front_primesense_y} ${front_primesense_z}" rpy="0 0 0"/>
    </xacro:realsense_camera>

    <xacro:realsense_camera name="xtion_back" parent="base_link">
        <origin xyz="${back_xtion_x} ${back_xtion_y} ${back_xtion_z}" rpy="0 0 ${M_PI}"/>
    </xacro:realsense_camera>
</robot>
