<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="arm_origin_x" value="0.12"/>
    <xacro:property name="arm_origin_y" value="0"/>
    <xacro:property name="arm_origin_z" value="0.69"/>
    <xacro:property name="shoulder_base_link_length" value="0.06"/>
    <xacro:property name="shoulder_link_length" value="0.41"/>
    <xacro:property name="elbow_link_length" value="0.32"/>
    <xacro:property name="wrist_deviation_link_length" value="0.09"/>
    <xacro:property name="wrist_extension_link_length" value="0.10"/>

    <joint name="arm_origin_joint" type="fixed">
        <parent link="base_link"/>
        <child link="arm_origin_link"/>
        <origin xyz="${arm_origin_x} ${arm_origin_y} ${arm_origin_z}" rpy="0 0 0"/>
    </joint>

    <link name="arm_origin_link"/>

    <joint name="arm_base_joint" type="prismatic">
        <axis xyz="0 0 1"/>
        <parent link="arm_origin_link"/>
        <child link="arm_base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <limit effort="1000.0" lower="0" upper="0.4" velocity="0.5"/>
    </joint>
    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="0.1 0.1 0.04"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.04"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>

    <joint name="shoulder_rotation_joint" type="revolute">
        <axis xyz="0 0 1"/>
        <parent link="arm_base_link"/>
        <child link="shoulder_base_link"/>
        <limit effort="1000.0" lower="${-M_PI/2}" upper="${M_PI/2}" velocity="0.5"/>
        <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}"/>
    </joint>
    <link name="shoulder_base_link">
        <visual>
            <geometry>
                <cylinder length="${shoulder_base_link_length}" radius="0.04"/>
            </geometry>
            <origin xyz="0 0 ${shoulder_base_link_length/2}" rpy="0 0 ${M_PI}"/>
            <material name="red"/>
        </visual> 
        <collision>
            <geometry>
                <cylinder length="${shoulder_base_link_length}" radius="0.04"/>
            </geometry>
            <origin xyz="0 0 ${shoulder_base_link_length/2}" rpy="0 0 ${M_PI}"/>
        </collision> 
        <inertial>
            <mass value="1"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>

    <joint name="shoulder_flexion_joint" type="revolute">
        <axis xyz="1 0 0"/>
        <parent link="shoulder_base_link"/>
        <child link="shoulder_link"/>
        <limit effort="1000.0" lower="0" upper="${M_PI/2}" velocity="0.5"/>
        <origin xyz="0 0 ${shoulder_base_link_length}" rpy="${-M_PI/2} 0 ${M_PI}"/>
    </joint>
    <link name="shoulder_link">
        <visual>
            <geometry>
                <cylinder length="${shoulder_link_length}" radius="0.04"/>
            </geometry>
            <origin xyz="0 0 ${shoulder_link_length/2}" rpy="0 0 0"/>
            <material name="blue"/>
        </visual> 
        <collision>
            <geometry>
                <cylinder length="${shoulder_link_length}" radius="0.04"/>
            </geometry>
            <origin xyz="0 0 ${shoulder_link_length/2}" rpy="0 0 0"/>
        </collision> 
        <inertial>
            <mass value="1"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>
    
    <joint name="elbow_joint" type="revolute">
        <axis xyz="1 0 0"/>
        <parent link="shoulder_link"/>
        <child link="elbow_link"/>
        <limit effort="1000.0" lower="0" upper="${M_PI}" velocity="0.5"/>
        <origin xyz="0 0 ${shoulder_link_length}" rpy="0 0 ${M_PI}"/>
    </joint>
    <link name="elbow_link">
        <visual>
            <geometry>
                <cylinder length="${elbow_link_length}" radius="0.04"/>
            </geometry>
            <origin xyz="0 0 ${elbow_link_length/2}" rpy="0 0 0"/>
            <material name="white"/>
        </visual> 
        <collision>
            <geometry>
                <cylinder length="${elbow_link_length}" radius="0.04"/>
            </geometry>
            <origin xyz="0 0 ${elbow_link_length/2}" rpy="0 0 0"/>
        </collision> 
        <inertial>
            <mass value="1"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>

    <joint name="wrist_deviation" type="revolute">
        <axis xyz="0 1 0"/>
        <parent link="elbow_link"/>
        <child link="wrist_deviation_link"/>
        <limit effort="1000.0" lower="${M_PI/2}" upper="${M_PI*3/2}" velocity="0.5"/>
        <origin xyz="0 0 ${elbow_link_length}" rpy="${M_PI} 0 ${M_PI}"/>
    </joint>
    <link name="wrist_deviation_link">
        <visual>
            <geometry>
                <cylinder length="${wrist_deviation_link_length}" radius="0.04"/>
            </geometry>
            <origin xyz="0 0 ${wrist_deviation_link_length/2}" rpy="0 0 0"/>
            <material name="green"/>
        </visual> 
        <collision>
            <geometry>
                <cylinder length="${wrist_deviation_link_length}" radius="0.04"/>
            </geometry>
            <origin xyz="0 0 ${wrist_deviation_link_length/2}" rpy="0 0 0"/>
        </collision> 
        <inertial>
            <mass value="1"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>

    <joint name="wrist_extension" type="revolute">
        <axis xyz="1 0 0"/>
        <parent link="wrist_deviation_link"/>
        <child link="wrist_extension_link"/>
        <limit effort="1000.0" lower="${M_PI/2}" upper="${M_PI*3/2}" velocity="0.5"/>
        <origin xyz="0 0 ${wrist_deviation_link_length}" rpy="0 ${M_PI} 0"/>
    </joint>
    <link name="wrist_extension_link">
        <visual>
            <geometry>
                <cylinder length="${wrist_extension_link_length}" radius="0.04"/>
            </geometry>
            <origin xyz="0 0 ${wrist_extension_link_length/2}" rpy="0 0 0"/>
            <material name="blue"/>
        </visual> 
        <collision>
            <geometry>
                <cylinder length="${wrist_extension_link_length}" radius="0.04"/>
            </geometry>
            <origin xyz="0 0 ${wrist_extension_link_length/2}" rpy="0 0 0"/>
        </collision> 
        <inertial>
            <mass value="1"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>
</robot>
